import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";

const font = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js i18n template",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en-US" }, { lang: "ge" }];
}

export default function Root({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang={params.lang}>
      <body className={font.className}>{children}</body>
    </html>
  );
}
